version: 2.1

defaults: &defaults
  working_directory: ~/negative
  docker:
    - image: circleci/node:10-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/negative
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: NODE_ENV=production CI="" yarn build
      - persist_to_workspace:
          root: .
          paths: .

  deploy-featurepeek:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/negative
      - checkout
      - run:
          name: Create Preview Link
          command: bash <(curl -s https://peek.run/ci)

  deploy-production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/negative
      - checkout
      - run: sudo apt-get install python-dev python-pip
      - run: sudo pip install awscli
      - run: aws s3 sync dist s3://computer-sanctuary-negative/ --delete
      - run: aws s3 cp dist/index.html s3://computer-sanctuary-negative/index.html --cache-control max-age=0 --content-type "text/html"
      - run: aws s3 cp dist/emissions.html s3://computer-sanctuary-negative/emissions --cache-control max-age=0 --content-type "text/html"
      - run: aws s3 cp dist/offsetting.html s3://computer-sanctuary-negative/offsetting --cache-control max-age=0 --content-type "text/html"
      - run: aws s3 cp dist/clients.html s3://computer-sanctuary-negative/clients --cache-control max-age=0 --content-type "text/html"
      - run: aws s3 cp dist/resources.html s3://computer-sanctuary-negative/resources --cache-control max-age=0 --content-type "text/html"
      - run: curl --location --request POST "https://www.spirit.fish/api/v1/renderers/b9285e1a-014f-4af3-90e2-f8f5ea2f46a8/api_invalidations" -H "Content-Type:application/json" -H "X-Hatchery-Renderer-Api-Key:$PRODUCTION_SPIRIT_FISH_API_KEY" --data-raw '{"invalidation":{"pages":["*"]}}'

workflows:
  build:
    jobs:
      - build
      - deploy-featurepeek:
          requires:
            - build
          filters:
            branches:
              ignore:
                - main
                - production
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: production
