version: 2.1

defaults: &defaults
  working_directory: ~/negative
  docker:
    - image: circleci/node:10-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/negative
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: NODE_ENV=production CI="" yarn build
      - persist_to_workspace:
          root: .
          paths: .

  deploy-featurepeek:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/negative
      - checkout
      - run:
          name: Create Preview Link
          command: bash <(curl -s https://peek.run/ci)

  deploy-production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/negative
      - checkout
      - run: cp dist/emissions.html dist/emissions
      - run: cp dist/offsetting.html dist/offsetting
      - run: cp dist/clients.html dist/clients
      - run: cp dist/resources.html dist/resources
      - run: npx firebase deploy -m "Deploy from CI" --non-interactive --token $FIREBASE_TOKEN

workflows:
  build:
    jobs:
      - build
      - deploy-featurepeek:
          requires:
            - build
          filters:
            branches:
              ignore:
                - main
                - production
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: production
